users/author/urls.py
"""main URL Configuration

"""
from django.conf.urls import include, url
from django.contrib import admin

from author import views
#from author.views import get_author_filter
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import cache_page


urlpatterns = [
	
	#url(r'^home/', views.HomeView.as_view()),
	url(r'^$', views.IndexView.as_view()),
	url(r'^regist/', views.Regist.as_view(), name = 'regist'),
    url(r'^login/$',  views.Login.as_view(), name = 'login'),
    url(r'^logout/$',  views.LogOut.as_view()),
    #url(r'^get_author/$', get_author_filter),
	url(r'^get_author/$', views.AuthorView.as_view(), name = 'get_author'),
	url(r'^get_author/(?P<pk>\d+)/$', views.GetAuthorView.as_view(), name= 'get_view'),
	url(r'^get_list/$',cache_page(60*15)(views.GetAuthorList.as_view()), name = 'get_list'),
	url(r'^get_save/$', views.SaveView.as_view(), name = 'get_save'),

	url(r'^thanks/', views.ThanksView.as_view(), name = 'thanks'),
	url(r'^avatar/$', views.Avatar.as_view(), name = 'avatar'),
	url(r'^set_timezone/$', views.set_timezone, name = 'set_timezone'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/main/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('author.urls')),
    url(r'^api/', include('my_rest.urls', namespace='my_rest')),
    url(r'^api-docs/', include('rest_framework_swagger.urls')),

]

users/author/models.py
from django.db import models
#from django.contrib.auth.models import User

class Author(models.Model):
	first_name = models.CharField(max_length=30)
	last_name = models.CharField(max_length=40)
	email = models.EmailField()

 	avatar = models.ImageField(upload_to = 'avatars/', default="index.jpg")

	def __unicode__(self):
		return '{0} {1} {2} {3}'.format(self.first_name, self.last_name, self.email, self.avatar)

class Book(models.Model):
	author = models.ForeignKey(Author)
	name = models.CharField(max_length=100)
	
	def __unicode__(self):
		return '{0} - {1}'.format(self.author, self.name)

class Reader(models.Model):
	name = models.CharField(max_length = 100)
	book = models.ManyToManyField(Book)

	def __unicode__(self):
		return '{0} {1}'.format(self.name, self.book)

users/author/forms.py
from django import forms
from models import Author, Book, Reader


class AuthorForm(forms.ModelForm):
	class Meta:
		model = Author
		fields = '__all__'

users/author/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, render_to_response, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView, DetailView, ListView
from django.views.generic.edit import FormView, View, UpdateView
from author.models import  Author

from forms import AuthorForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

from author.forms import AuthorForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.sessions.models import Session
import json
import pytz
import datetime
from django.core import serializers
from django.views.decorators.cache import cache_page

class HomeView(TemplateView):
    template_name ='author/home.html'
    #template_name ='testapp/home2.html'
    #template_name ='testapp/home3.html'
    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)

        context['author_name'] = get_author()
            

        context['books'] = get_books()
        context['list'] = get_list()

        return context

def get_author_filter(request):
    #Author.filter_author.get_author()
    #if request.POST:
    form = AuthorForm()
    return HttpResponse(form)

class AuthorView(FormView):
    form_class = AuthorForm
    template_name = 'author/author.html'
    success_url = '/critic/thanks'
    #def post(self, request,*args,**kwargs):
 
    def form_valid(self,form):
        self.object = form.save()
        print self.object
        return super(AuthorView, self).form_valid(form)

    @method_decorator(login_required(login_url='/login/'))
    def dispatch(self, *args, **kwargs):
        return super(AuthorView, self).dispatch(*args, **kwargs)


'''
class GetAuthorView(DetailView):
    model = Author
    template_name = 'author/author_view.html'

    @method_decorator(login_required(login_url='/login/'))
    def dispatch(self, *args, **kwargs):
        return super(GetAuthorView, self).dispatch(*args, **kwargs)
'''

class GetAuthorView(UpdateView):
    model = Author
    template_name = 'author/author_view.html'
    fields = '__all__'
    success_url = '/get_list/'

    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        print self.object
        form_class = AuthorForm(instance=self.object)
        print form_class.fields
        author = Author.objects.get(first_name = 'Bob')
        print 1
        request.session['user_author'] = author.first_name
        kwargs.update({'user_author': author.first_name})
        print kwargs
        print 2
        # user_author = request.session['user_author']
        # print request.session['user_author']
        # return user_author
        return super(GetAuthorView, self).get(request, *args, **kwargs)

    @method_decorator(login_required(login_url='/login/'))
    def dispatch(self, *args, **kwargs):
        return super(GetAuthorView, self).dispatch(*args, **kwargs)

    # def get(self, request, *args, **kwargs):
        # print 1


class GetAuthorList(ListView):
    model = Author
    template_name = 'author/author_view_list.html'

    def get_context_data(self, **kwargs):
        context = super(GetAuthorList, self).get_context_data(**kwargs)
        context.update({'user_author': self.request.session['user_author']})
        return context
    
    def post(self,request,*args,**kwargs):
        q = request.POST.get('search','Bill')
        u = request.POST.get('up','')
              
        search = Author.objects.filter(first_name__icontains=q)
        
        if u =='up':
            search = search.order_by('id')
        else:
            search = search.order_by('-id')
        # up = Author.objects.filter(first_name__icontains=q).order_by('first_name')
        # down = Author.objects.filter(first_name__icontains=q).order_by('-first_name')
        #search = Author.objects.filter(first_name__istartswith=q)
        return render(request,self.template_name,
            {'author_list': search})

   
    @method_decorator(login_required(login_url='/login/'))
    def dispatch(self, *args, **kwargs):
        return super(GetAuthorList, self).dispatch(*args, **kwargs)

 
    
'''

class GetAuthorSave(UpdateView):
    model = Author
    template_name = 'author/author_view.html'
    success_url = '/get_save/'
    
    


    @method_decorator(login_required(login_url='/login/'))
    def dispatch(self, *args, **kwargs):
        return super(GetAuthorSave, self).dispatch(*args, **kwargs)
 '''


class Regist(FormView):
    form_class = UserCreationForm
    success_url = '/get_save/'
    template_name = 'author/regist.html'

    def form_valid(self,form):
        self.object = form.save()
        return super(Regist, self).form_valid(form)


class Login(FormView):
    form_class = AuthenticationForm
    success_url = '/get_list/'
    template_name = 'author/login.html'

    def form_valid(self,form):
        user = form.get_user()
        login(self.request, user)
        return super(Login, self).form_valid(form)


class LogOut(View):
    success_url = '/regist/'
    template_name = 'author/base.html'

    def get(self,request):
        logout(request)
        return HttpResponseRedirect('/login')

class Avatar(FormView):
    template_name = 'author/avatar.html'
    form_class = AuthorForm
    success_url = '/get_save/'

    def form_valid(self, form):
        form.save()
        return super(Avatar, self).form_valid(form)

    def ses(request):
        form_list = []
        #request.session['avatar'] = avatar
        form_list = request.session['form_list']
        form_list.append(avatar)
        request.session['form_list'] = form_list

    @method_decorator(login_required(login_url='/login/'))
    def dispatch(self, *args, **kwargs):
        return super(Avatar, self).dispatch(*args, **kwargs)


    

class ThanksView(TemplateView):
    template_name ='thanks/'

class IndexView(TemplateView):
    model = Author
    template_name = 'author/index.html'

class SaveView(TemplateView):
    model = Author
    template_name = 'author/save.html'


def set_timezone(request):
    template_name = 'author/set_timezone.html'
    if request.method == 'POST':
        request.session['django_timezone'] = request.POST['timezone']
        return redirect('/')
    else:
        return render(request,template_name,
                        {'timezones': pytz.common_timezones,
                        'TIME_ZONE':'Europe/Kiev', 'time': datetime.datetime.now()})

users/author/templates/author/author.html
{% extends "author/base.html" %}

{% block title %}Django !{% endblock %}

{% block content %}
    <hr>
    <div class="form-group col-xs-12">
        
        <form method='post' action={% url 'get_author' %}>{% csrf_token %}
            {{form.as_p}}
        <br>
        <button type="submit" class="btn btn-primary btn-lg active" value="Send"> Send</button>
        
    </div>
        </form>
        
      
{% endblock %}

users/author/templates/author/author_view.html
{% extends 'author/base.html' %}

{% block title %}Django !{% endblock %}
 
{% block content %}
    
    <h3>Information about author</h3>
    {{user_author}}
     <center><img id="avatar" width="150px" height="150px"  src="{{ author.avatar.url}}" class="media-object"></center>
    }

    <form method='post' action='' role="form">{% csrf_token %}
    <div class="form-group col-md-6 col-md-offset-3">
    	<label for="first_name"> First name:</label><textarea class="form-control" id="id_text" name="first_name" rows=1 width="50px" >{{author.first_name}}</textarea>
         

    </div>
    <div class="form-group col-md-6 col-md-offset-3">
		<label for="last_name" >Last name:</label> <textarea class="form-control" id="id_text" name="last_name" rows=1  width="50px" >{{author.last_name}}</textarea>
       
	</div>
	<div class="form-group col-md-6 col-md-offset-3">
		<label for="email">Email:</label> <textarea class="form-control" id="id_text" name="email" rows=1>{{author.email}}</textarea>
       
    </div>
    <div class="form-group col-md-6 col-md-offset-3">
        <label for="avatar">Avatar:</label> <input type='file' id="id_text" name="avatar">{{author.avatar}}</input>
    </div>
<div class="form-group col-md-6 col-md-offset-3">
    <button type="submit" class="btn btn-success" value="Save"> Save</button>
     <br>
     <a href="../../get_list/"> Authors </a> 
     </div>
    </form>
     
{% endblock %}

users/author/templates/author/author_view_list.html
{% extends 'author/base.html' %}

{% block title %}Django !{% endblock %}

{% block content %}
     

</form>
<div class="col-md-6 col-md-offset-3"> 

<a href="../avatar/"><button type="button" class="btn btn-default btn-lg"><span class="glyphicon glyphicon-user"></span> Add new author</button></a>

</div>
    <div class="panel panel-default col-md-6 col-md-offset-3">
        <!-- Default panel contents -->

        <div>Последний автор которого вы просматривали: {{user_author}}</div>
        <div class="panel-heading">List of authors:</div>
        <div class="panel-body">
        <p><form action='' method='post'>{% csrf_token %}
        <input type="radio" name="up" value = up> Up<Br>
        <input type="radio" name="up" value = down> Down<Br>
        <input id="id_author" maxlength="40" name="search" type="text" class="form-control" placeholder="Search" /></p>
        </div>

         <!-- List group -->
         {% for o in author_list %}
        <ul class="list-group">
        <li class="list-group-item"><a href="{%url 'get_view' o.pk%}">{{o.pk}}: {{o.first_name}}<br> 
        {{o.last_name}}<br>
        {{o.email}}<br>

        </li>
        </ul>
        {% endfor %}
    
     </form>
    <div id='test_list' >
            
    </div>
    <script >
        $.get("http://127.0.0.1:8000/api/list/", function(rez){
        //$("#test_list").append("<p>Test</p>");
        rez.forEach(function(item){
            $("#test_list").append("<p>"+item.first_name+"</p>");
        });
     });

    </script> 

	</div>
        
{% endblock %}

users/author/templates/author/avatar.html
{% extends 'author/base.html' %}

{% block title %}Django !{% endblock %}
 
{% block content %}

<div>
    <hr>
    <form method="POST" action={% url 'avatar' %} enctype="multipart/form-data">
            {% csrf_token %}
     
    <div class="form-group col-md-6 col-md-offset-3">
    	<label for="first_name"> First name:</label>{{form.first_name}}
   

    </div>
    <div class="form-group col-md-6 col-md-offset-3">
		<label for="last_name" >Last name:</label> <!--<textarea id="id_text" name="last_name" rows=1>{{author.last_name}}</textarea>-->
       {{ form.last_name}}
	</div>
	<div class="form-group col-md-6 col-md-offset-3">
		<label for="email">Email:</label> <!--<textarea id="id_text" name="email" rows=1>{{author.email}}</textarea>-->
       {{ form.email}}
    </div>
    <div class="form-group col-md-6 col-md-offset-3">
        <label for="avatar">Avatar:</label> {{ form.avatar}}

    </div>
	<div class="form-group col-md-6 col-md-offset-3">
	<hr>
     	<input type="submit" class='btn btn-primary' value="Save user" />
	</div>
      
    </form>          



     


   

</div>
{% endblock %}

users/author/templates/author/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Bootstrap -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script> 
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-inverse" role="navigation">
     <a href='../logout'>{% if  user.is_authenticated %}
                        Exit
                        {% endif %}</a>
    <a href="../login/"> {% if not user.is_authenticated %}
                        LogIn
                        {% endif %}
    </a> 

    {% if user.is_authenticated %}
        {{user.username}}
    {% else%}
    <a href='../regist/'>Registration</a>
    {% endif %}
    <a href="../../get_list/"> {% if user.is_authenticated %}
                        Authors
                        {% endif %}
    </a> 
</nav>


<div class="jumbotron">
 <h1><center>Welcome to my site {{user.username}}</center></h1>

 </div>
    {% block content %}


    {% endblock %}


{% block footer %}
    <div class="col-xs-offset-6 col-sm-offset-4 col-xs-6 col-sm-4 col-xs-offset-6 col-sm-offset-4">
    <p ><center>Thanks for visiting my site.</center></p>
    </div>
{% endblock %}

</body>
</html>

users/author/templates/author/base1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

 <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="jumbotron-narrow.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">
      <div class="header">
        <nav class="navbar navbar-inverse" role="navigation">
        <ul class="nav nav-pills pull-right">
          <li class="active">{% if user.is_authenticated %}
        {{user.username}}
    {% else%}
        <a href='../regist/'>Registration</a>
    {% endif %}</li>
          <li><a href='../logout'>Exit</a></li>
          <li><a href="../login/">LogIn</a></li>
        </ul>
        <nav class="navbar navbar-inverse" role="navigation">
        <h3 class="text-muted">{{user.username}}</h3>
      </div>

      <div class="jumbotron">
        <h1>Welcome to my site</h1>
         {% block content %}


          {% endblock %}
        
      </div>
    </div>
      

      <div class="footer">
    {% block footer %}
    
    <p><center>Thanks for visiting my site.</center></p>
    {% endblock %}
      </div>

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>

users/author/templates/author/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
 
    <title>Ok Django!</title>

    <!-- Bootstrap -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
    
  </head>
  <body>
  <h1>Authors</h1>
  Hi there!
  {{author_name}}<br><br>
  {{books}}
  <br><br><br>
  <div class="container-fluid">
    <div class="row">
       <div class="col-xs-4">
     <!--  {%for author in author_name %}
       	<p class="bg-primary">{{author}} </p>
        {% endfor %}
        </div>-->
        
     <div class="col-xs-12">
      	<ul class="list-group">
          <!--<li class="list-group-item">{{ book }} </li>-->
      	 {%for author in author_name %}
      			<li class="list-group-item">{{ author }} </li>
      		{% empty %}
      			<li> No books</li>
      		{% endfor %}
      	</ul>
        <ul class="list-group">
          <!--<li class="list-group-item">{{ book }} </li>-->
         
            <li class="list-group-item">{{ book }} </li>
          
            
        </ul>
      </div>
  
    </div>
  </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  </body>
</html>

users/author/templates/author/index.html
{% extends 'author/base.html' %}

{% block title %}Django !{% endblock %}

{% block content %}
    
    {% if user.is_authenticated %}
        <a href='../get_list/'>Author</a>
    {% else%}
        Please <a href='../regist/'>Register</a> or <a href='../login/'>Login </a>
    {% endif %}

{% endblock %}

users/author/templates/author/login.html
{% extends 'author/base.html' %}

{% block title %}Django !{% endblock %}

{% block content %}


	<form role="form" action='' method='post'>{% csrf_token %}
  <div class="form-group col-xs-12 ">
    <label  for="username">Username:</label>{{form.username}}
</div>
    <div class="form-group col-xs-12 ">
    <label  for="pass">Password</label>{{form.password}}
  </div>
  <div class="form-group col-xs-12 ">
     <button type="submit" class="btn btn-default" value="Send"> Send</button>
  </div>
  
	</form>



 
<!--   <div class="container">

      <form class="form-signin" role="form" action='' method='post'>{% csrf_token %}
        <h2 class="form-signin-heading">Please sign in</h2>
        <input type="login" class="form-control" placeholder="Login" required autofocus>
        <input type="password" class="form-control" placeholder="Password" required>
        <label class="checkbox">
          <input type="checkbox" value="remember-me"> Remember me
        </label>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>

    </div>-->

  

{% endblock %}

users/author/templates/author/login_error.html
<h1>Please, Log In</h1>

users/author/templates/author/regist.html
{% extends 'author/base.html' %}

{% block title %}Django !{% endblock %}

{% block content %}
<div class="form-group col-xs-12">
    <form action='' method='post'>{% csrf_token %}
    {{form.as_p}}

    <button type="submit" class="btn btn-primary btn-lg active" value="Send"> Send</button>
    </form> 


</div> 


{% endblock %}

users/author/templates/author/save.html
{% extends "author/base.html" %}

{% block title %}Saved!{% endblock %}

{% block content %}

<h1><center> <p class="bg-primary">Successfully saved!!!</p></center></h1>

<a href='../get_list/'> Authors</a>       


{% endblock %}

users/author/templates/author/set_timezone.html
{% extends 'author/base.html' %}

{% block title %}Django !{% endblock %}
 
{% block content %}
    
{% load tz %}
<form >
   <!--  {% csrf_token %} -->
    <p>{{TIME_ZONE}} {{time}} {% now "js F Y H:i"%}</p>
    <label for="timezone">Time zone:</label>
    <select name="timezone">
        {% for tz in timezones %}
        <option value="{{ tz }}"{% if tz == TIME_ZONE %} selected="selected"{% endif %}>{{ tz }}</option>
        {% endfor %}
    </select>
    <input type="submit" value="Set" />
</form>

{% endblock %}

<!-- 
action="{% url 'set_timezone' %}" method="POST" -->

users/author/templates/author/thanks.html
<h1>THANKS YOU!!!</h1>